notifications:
  email: false

language: ruby
sudo: required
addons:
  chrome: stable
rvm:
  - 2.4
  - 2.3.3

env:
 - "RAILS_VERSION=4.2.9"
 - "RAILS_VERSION=5.0.6"
 - "RAILS_VERSION=5.1.4"

before_install:
  - gem install bundler
